### ISSUE TITLE
[ISSUE]

### ISSUE THREAD

**Issue by wildturk** [eltreum0/eltruism#119]
![WoWScrnShot_051123_073908](https://github.com/eltreum0/eltruism/assets/2428988/7b0a9334-d1b4-439e-872b-6c233fd9ca6a)
When exiting combat i am getting above error 

**To Reproduce**
3. Do '....'

**Expected behavior**

**Screenshots**

**Addon Versions (please complete the following information):**
 - ElvUI version:13.32
 - AddonSkins version: 3.8.6
 - Any other addons used: [e.g. Details, BigWigs, ProjectAzilroka so on]

**Additional context**

**Comment by eltreum0** [comment]
you didnt list any of the other addons used, also are you using arkinventory? it seems to be a common theme for this error to happen when using it

besides its fixed in dev

**Comment by eltreum0** [comment]
dev version released with the fix

**Comment by eltreum0** [comment]
good to know ty, but the version with the fix was released

**Comment by wildturk** [comment]
Great, thanks! Love the skin by the way.
