### ISSUE TITLE
[ISSUE] Can't find how to change background texture

### ISSUE THREAD

**Issue by Chivsss** [eltreum0/eltruism#120]
**Describe the bug**
Hi,
I want to change the background texture of my entire interface (nameplate, chat, action bars ...)
Currently there are small slanting bars everywhere. 

I looked for the solution but couldn't find it.

**To Reproduce**
1. During installation process everything is ok
2. After the last /reload the texture changes

**Expected behavior**
I want to now how can i change it ?

**Screenshots**

![WoWScrnShot_060723_083833](https://github.com/eltreum0/eltruism/assets/135806723/431caccb-bfab-44a4-9235-879c4f7e1044)

**Addon Versions (please complete the following information):**
Every addons are up to date

Thanks a lot for your help !

**Comment by eltreum0** [comment]
go to skins > addons > elvui and change or disable it there

**Comment by Chivsss** [comment]
Hi

Thanks for the fast reply !!!!

👌🏼👌🏼
