### ISSUE TITLE
[ISSUE]

### ISSUE THREAD

**Issue by cr00k3r** [eltreum0/eltruism#124]
**Describe the bug**
Blizzard Nameplates showing along with Elvui\Eltruism nameplates.

**To Reproduce**
N\A

**Expected behavior**
N\A

**Screenshots**
![image](https://github.com/eltreum0/eltruism/assets/1480663/3d921896-178a-4489-a07d-1c03d1a32711)

**Addon Versions (please complete the following information):**
 see screenshot

**Additional context**
Started around reset this week.

**Comment by eltreum0** [comment]
does it happen with `/eltruismdebug on` ?

**Comment by eltreum0** [comment]
This is likely another addon causing it, such as using multiple nameplate addons

Futhermore Eltruism does not add nameplates, they are from ElvUI, if they disappear with the debug mode then its another addon and you'll have to figure out which one
