### ISSUE TITLE
[ISSUE]

### ISSUE THREAD

**Issue by Ivankonoiko** [eltreum0/eltruism#130]
What is the issue you are having?
Randomly on Arenas 2x2 enemyplayer nameplate just dissapear from start, it's can happend for both enemy players or just for one of them after Elvui update to 13.40. Sometimes everything is working how it supposed to be.
I'm using Addonskins v4.68, Elvui Eltruism Wrath v3.9.6 Elvui WrathArmory v1.08

What is the expected behavior?
normal nameplates above enemy models

What actually happened?
health bar, castbar, icons of debuffs/buffs/ and so on just not existed above enemy player on some arenas.
![изображение_2023-09-09_002102602](https://github.com/eltreum0/eltruism/assets/62277076/655e749e-27f0-40fd-8560-f39e7a82a34f)

**Comment by eltreum0** [comment]
This isnt controlled by Eltruism, i suggest you grab BugSack + BugGrabber and see if you are getting errors
