### ISSUE TITLE
[ISSUE] Lagging when hovering over quest tracker

### ISSUE THREAD

**Issue by Mathayus26** [eltreum0/eltruism#141]
At random moments, but mostly after a while of playing, the game starts to stutter/lag/fps drop heavily when hovering over the Quest Tracker. This happens most of the times after a dungeon, or when coming back from AFK. The only way to solve it is to Reload UI.
I have Questie enabled, also playing WOTLK classic as a Warlock.

 - ElvUI version: 13.46
 - Eltruism version: 4.02
 - Any other addons used: All the addons suggested in the Eltruism's addon page

**Comment by eltreum0** [comment]
Did you try using `/eltruismdebug on`?

**Comment by Mathayus26** [comment]
No, what does it do?

**Comment by eltreum0** [comment]
> No, what does it do?

disables other addons, try that and see if you still have issues

**Comment by Mathayus26** [comment]
I see; I am currently trying, will update you soon!

**Comment by Mathayus26** [comment]
Everything's good for now; could it be Questie? altho I thought they were compatible.. :(

**Comment by eltreum0** [comment]
> Everything's good for now; could it be Questie? altho I thought they were compatible.. :(

they should be yes, could be another addon. in fact if you are using questie disable everything and try only questie if it happens then you have found out a bug in questie you should report

**Comment by Mathayus26** [comment]
I also noticed that sometimes the Tracker gets bugged and it doesnt load the quest log on left click; you have to right-click, open quest details to "reset" it and have it work with left click.

**Comment by eltreum0** [comment]
> I also noticed that sometimes the Tracker gets bugged and it doesnt load the quest log on left click; you have to right-click, open quest details to "reset" it and have it work with left click.

if you are using questie thats a questie issue not eltruism

**Comment by Mathayus26** [comment]
Oh ok! Good to know!
I love your Ui btw! Really love it

**Comment by Mathayus26** [comment]
Alright so.. I've been playing a bit and it seems the problem is solved: the only addon I've kept disabled is Rare scanner, could be the culprit. Another thing started popping up now though: an error regarding "blizzard arena" lua, whenever I go through a loading screen (i.e. changing zone): 
![image](https://github.com/eltreum0/eltruism/assets/74601845/20198ffd-7e9d-4dd6-bbe5-f1f05e2154ba)

**Comment by eltreum0** [comment]
that looks like it might be a blizzard error, or a pvp addon error

**Comment by Mathayus26** [comment]
I only have Gladdy on (which you support); the error comes up even without

**Comment by eltreum0** [comment]
like i said tho, and you have demonstrated, if it doesnt happen with `/eltruismdebug on` then that means its another addon

if you want more help, feel free to join the discord as this is not related to eltruism

**Comment by Mathayus26** [comment]
Ok thanks, sorry for disturbing you; will search for reddit!
