### ISSUE TITLE
[ISSUE] Action Bars moving when logging, hearthing, and /reload

### ISSUE THREAD

**Issue by claprime98** [eltreum0/eltruism#142]
**Describe the bug**
After configuring an Eltruism profile to be how I'd like it, whenever I log back in after logging out, use my hearthstone, or do /reload, my bars move. Just installed and configured Eltruism yesterday so haven't really done much else to see what else will trigger this, have only seen it happen due to re-logging, hearthing, and doing /reload so far. See screenshots section for more details

**To Reproduce**
1. Login as any character
2. Configure action bars to desired positions
3. Log out of character
4. Log back in to same character
5. Note action bar positions, re-configure if necessary
6. Use hearthstone
7. Note action bar positions, re-configure if necessary
8. Do /reload
9. Note action bar positions, re-configure if necessary

**Expected behavior**
Action bars should stay in desired positions unless/until changed.

**Screenshots**
(Configured bars)
![image](https://github.com/eltreum0/eltruism/assets/43456523/af836d03-a3aa-45d6-b03d-ee6c864ff6eb)
![image](https://github.com/eltreum0/eltruism/assets/43456523/629c6717-2786-4c38-9623-3061e41a8301)

(Bars after re-logging/hearthing/reload)
![image](https://github.com/eltreum0/eltruism/assets/43456523/595260d1-e9d8-42d7-bca2-c846b05bedc9)
![image](https://github.com/eltreum0/eltruism/assets/43456523/4ee96f48-0992-41c9-aa15-720b1189e956)

**Addon Versions (please complete the following information):**
 - ElvUI version: 13.45
 - Eltruism version: 4.0.2
 - DBM
 - Details
 - Auctionater
 - Pawn
 - HandyNotes
 - SumlationCraft
 - Raider.IO

**Additional context**
I have already tried reproducing the issue with all addons except for ElvUI and Eltruism disabled, and the issue persists unfortunately.

NOTE: Edit was just to add note of issue happening during /reload to Description section. Noticed issue occurs doing /reload while writing issue report so forgot to include in some places

NOTE 2:While I did try manually disabling all addons except for ElvUI & Eltruism, did not yet try /eltruismdebug on as suggested in other closed issues. Just tried that and issue still persists.

**Comment by eltreum0** [comment]
You have borders enabled, which with my profile has Auto Adjust.

Auto adjust moves the bars and the borders and their sizes to avoid overlap, if you want to make changes disable Auto Adjust in Eltruism > Borders

Or type `/eltruism autoadjust` to more easily disable it

**Comment by claprime98** [comment]
That fixed it, thank you!

**Comment by eltreum0** [comment]
No problem!
