### ISSUE TITLE
talent page is big fullscreen[ISSUE]

### ISSUE THREAD

**Issue by TROLOGY** [eltreum0/eltruism#146]
hi i heve a problem  and that is that my talent page is fullscreen and even i cant see the specialization sheet.so if i want to make it normal i must disable ElvUI Eltruism or a wast time fix that in ElvUI_MerathilisUI there is a check option on scale and if on and off that check and change the size of talent on there itwill be fis for a reload time

**Comment by eltreum0** [comment]
Eltruism > Skins > General > Blizzard > Talents Scale 

Default is 1, maybe you increased or imported a profile with a higher value

**Comment by TROLOGY** [comment]
yes i get a profile. and this way u write for i did it and it works a little. but its still big yet

**Comment by eltreum0** [comment]
> yes i get a profile. and this way u write for i did it and it works a little. default of it was 1 i reduce it to lowest number and its still big yet

if its still big then you got another addon also scaling it and using a higher value, do `/eltruismdebug on` and see how it works/looks

**Comment by TROLOGY** [comment]
no sir its  not fix yet 
![Uploading Untitled 1.png…]()
![Uploading Untitled 2.png…]()
![Uploading Untitled.png…]()
![Uploading Untitled3.png…]()

**Comment by eltreum0** [comment]
whatever pictures you tried to upload failed, its just the link to this issue

**Comment by TROLOGY** [comment]
![Uploading Untitled 1.png…]()
![Uploading Untitled 2.png…]()
![Uploading Untitled 4.png…]()
![Uploading Untitled.png…]()
![Uploading Untitled3.png…]()

**Comment by TROLOGY** [comment]
![Uploading Untitled.png…]()

**Comment by TROLOGY** [comment]
![Untitled](https://github.com/eltreum0/eltruism/assets/151449447/83c97ca1-7425-4b52-bc21-de15a7f9a094)

**Comment by TROLOGY** [comment]
![Untitled1](https://github.com/eltreum0/eltruism/assets/151449447/51122a3d-2108-4616-9abb-16ef9200239f)

**Comment by TROLOGY** [comment]
![Untitled 1](https://github.com/eltreum0/eltruism/assets/151449447/bf98ceef-e8de-477b-814a-c22f5c8db080)

**Comment by TROLOGY** [comment]
![Uploading Untitled 2.jpg…]()

**Comment by TROLOGY** [comment]
![Uploading Untitled 2.jpg…]()

**Comment by TROLOGY** [comment]
![Untitled 2](https://github.com/eltreum0/eltruism/assets/151449447/b3808597-513f-4a33-a33e-2c7f08f2ba67)

**Comment by TROLOGY** [comment]
![Untitled3](https://github.com/eltreum0/eltruism/assets/151449447/cbb3a83f-832a-4884-b317-91f33b796e62)

**Comment by eltreum0** [comment]
that does not look like my scale for talents

**Comment by eltreum0** [comment]
do `/eltruismdebug on`

**Comment by eltreum0** [comment]
![image](https://github.com/eltreum0/eltruism/assets/30246110/21c57489-8792-4e91-8404-50ae75c0c590)

Indeed you seem to be adjusting Merathilis's scale, disable his scale or mine and use only one. Mine goes from 0.1 to 1.3 and his seems to be 0.5 to 2

**Comment by TROLOGY** [comment]
> do `/eltruismdebug on`
i did but it get worse.the details , platers and some other addons didnt works

**Comment by eltreum0** [comment]
> > do `/eltruismdebug on`
> > i did but it get worse.the details , platers and some other addons didnt works

do `/eltruismdebug off`, the debug mode disables other addons for debug purposes
