### ISSUE TITLE
Actionbars positions cant locked

### ISSUE THREAD

**Issue by Kibitzertr** [eltreum0/eltruism#154]
First sorry for my bad English :/

I have a mmo mouse. And i use action bar keys looklike my mouse side buttons. I made an action bar 3 buttons per row, total 12 buttons and its ok. Looklike numpad keys and i use perfectly easy. 

But when i install Eltrusim 2 action bars always reset positions on center. i change positions, lock positions. When relog reset positions again.
![image](https://github.com/eltreum0/eltruism/assets/160329131/33ac7d44-5d7d-459b-8b2d-5fcd0b680650)
![image](https://github.com/eltreum0/eltruism/assets/160329131/8c39598c-d9e7-4d79-b7a9-60f3e50e2aaf)
And Reload 
![image](https://github.com/eltreum0/eltruism/assets/160329131/76b41deb-e93a-4458-931c-73bd0d05a1f4)
Action bar 3 and 4 change positions.

**Comment by eltreum0** [comment]
You likely enabled borders at some point, which autoadjusts the actionbars to make them fit with the borders

You have to disable the autoadjust, either in eltruism > borders or by running the /eltruism autoadjust command

**Comment by Kibitzertr** [comment]
Thank you. i disable auto adjust here and its ok now :D

![image](https://github.com/eltreum0/eltruism/assets/160329131/66b643cc-e047-4e4a-bd02-9956eb5e7f20)

**Comment by eltreum0** [comment]
good to hear, ty
