### ISSUE TITLE
[ISSUE] Character Panel Enchant Icon Duplicating

### ISSUE THREAD

**Issue by MattS8** [eltreum0/eltruism#157]
**Describe the bug**
After opening/closing the character panel multiple times, the icon representing the enchant on a piece of gear appears to duplicate. This seems to happen over and over again until the enchant icon runs off the screen.

**To Reproduce**
1. Open Character Panel
2. Close Character Panel
3. Open Character Panel again
4. (Potentially need to open and close a few times)

**Expected behavior**
Should only show the icon once

**Screenshots**
![Bug1](https://github.com/eltreum0/eltruism/assets/2137874/92dca5fc-f755-4d4c-a4ca-a96a7d997650)

**Addon Versions (please complete the following information):**
 - ElvUI version: 13.61
 - Eltruism version: 4.1.2
 - Any other addons used: 
   - mMT - Media Pack
   - mMT - mMediaTag & Tools

**Comment by eltreum0** [comment]
can you test with `/eltruismdebug on`?

**Comment by eltreum0** [comment]
I am unable to reproduce this issue, did you do this while in combat?

**Comment by MattS8** [comment]
This is out of combat. 

Enabling debugging and I get this LUA error:

```
Message: .../ElvUI_EltreumUI/Modules/Skins/Character/Sockets.lua:1562: attempt to concatenate field '?' (a nil value)
Time: Thu Apr 25 01:51:59 2024
Count: 1
Stack: .../ElvUI_EltreumUI/Modules/Skins/Character/Sockets.lua:1562: attempt to concatenate field '?' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_EltreumUI/Modules/Skins/Character/Sockets.lua"]:1562: in function `_AddEnchants'
[string "@Interface/AddOns/ElvUI_EltreumUI/Modules/Skins/Character/Sockets.lua"]:1428: in function `_Render'
[string "@Interface/AddOns/ElvUI_EltreumUI/Modules/Skins/Character/Sockets.lua"]:1421: in function `_Refresh'
[string "@Interface/AddOns/ElvUI_EltreumUI/Modules/Skins/Character/Sockets.lua"]:1380: in function `Refresh'
[string "@Interface/AddOns/ElvUI_EltreumUI/Modules/Skins/Character/Sockets.lua"]:1347: in function `callback'
[string "@Interface/AddOns/ElvUI_EltreumUI/Modules/Skins/Character/Sockets.lua"]:1173: in function <.../ElvUI_EltreumUI/Modules/Skins/Character/Sockets.lua:1171>
[string "=[C]"]: in function `Show'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:2168: in function `SetUIPanel'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:2013: in function `ShowUIPanel'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:1881: in function <Interface_Vanilla/FrameXML/UIParent.lua:1877>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:2660: in function `ShowUIPanel'
[string "@Interface_Vanilla/FrameXML/CharacterFrame.lua"]:26: in function <Interface_Vanilla/FrameXML/CharacterFrame.lua:4>
[string "=[C]"]: in function `ToggleCharacter'
[string "TOGGLECHARACTER0"]:1: in function <[string "TOGGLECHARACTER0"]:1>

Locals: (*temporary) = <function> defined =[C]:-1
```

**Comment by eltreum0** [comment]
this has also been asked in discord, apparently its due to some change in sod's enchants

I ask that you unequip each item one by one as you test, until you find the item that is causing the error then post the item + enchant it has so i can look into it because its seems specific to an item/enchant

**Comment by MattS8** [comment]
Some interesting observations:

I equipped each piece one-by-one and it was fine until I equipped  **Shrieking Spaulders** 
![image](https://github.com/eltreum0/eltruism/assets/2137874/ad31d916-0503-497c-a148-9c7d6153a050)

Unequipping this item and closing/reopening the character panel also seems to fix the visual error.

In addition, equipping this piece **also** causes the error: 
![image](https://github.com/eltreum0/eltruism/assets/2137874/8c50ed30-4b4a-440b-8525-44223b193de9)


My guess is that it has to do with the new crafting gear pieces.

**Comment by eltreum0** [comment]
Ok that appears to be the Atal'ai Signet of Might, it should work with dev, try grabbing the repo (on go on discord > bot-spam > !dev) and test with that

**Comment by eltreum0** [comment]
this commit might fix this issue, let me know if it works for you

**Comment by MattS8** [comment]
Seems to still have the bug for me.

**Comment by eltreum0** [comment]
guess ill have to clock those enchants in SOD then

**Comment by MattS8** [comment]
so far it seems fixed! Thanks!

**Comment by eltreum0** [comment]
Good to know, seems like the ids are kinda wonky in SOD
