### ISSUE TITLE
[REQUEST] Gradient Colors Export & Import

### ISSUE THREAD

**Issue by AngelosNaoumis** [eltreum0/eltruism#162]
**Is your feature request related to a problem? Please describe.**
I would like to have an option to somehow copy colors from one profile to another problem.

**Describe the solution you'd like**
A way to do an export/import of gradient colors saved by Elt

**Describe alternatives you've considered**
Copy paste colors 1 by 1 and implementing in the new profile

**Additional context**

**Comment by eltreum0** [comment]
Added, but due to the way the profile exists it will import the whole gradient settings, such as textures and which frames its enabled on
