### ISSUE TITLE
[REQUEST] Missing Borders options

### ISSUE THREAD

**Issue by AngelosNaoumis** [eltreum0/eltruism#163]
**Is your feature request related to a problem? Please describe.**
Some borders options are missing to make cohesive UI.

**Describe the solution you'd like**
Add following missing options to border

Player
->Class bar when detached from frame (currently works only for Spaced & attached to frame)

 Boss
->Power (Missing)
->Cast bar (Missing)
->Debuffs/buffs (unique size settings as most of the time its different sizes than unit frame auras)

Party
->Power (Missing)
->Cast bar (Missing)
->Debuffs/buffs (unique size settings as most of the time its different sizes than unit frame auras)
->Pet group
->Target group

Pet
->Power (Missing)
->Cast bar (Missing)
->Debuffs/buffs (unique size settings as most of the time its different sizes than unit frame auras)

Raid 1/2/3
->Power (Missing)
->Debuffs/buffs (unique size settings as most of the time its different sizes than unit frame auras)

Focus Target
->Power (Missing)

Tank
->Health (Missing)
->Target group(Missing)
->Debuffs/buffs (Missing)

Assist
->Health (Missing)
->Target group(Missing)
->Debuffs/buffs (Missing)

**Describe alternatives you've considered**
Attaching border with weakauras

**Additional context**
I will try to understand how you border stuff and maybe do a pull request.

**Comment by eltreum0** [comment]
class bar already exists, you have it disabled

Boss, party, pet, raid and focus target not getting added 

Tank and Assist might happen

Why? Because borders are extra frames and the game has a limit on the number of frames, i am not going to add many more borders because of this

**Comment by AngelosNaoumis** [comment]
updated description for classbar (wrong description on my end :D)

**Comment by eltreum0** [comment]
I've tested:

priest classbar (insanity and power) and they work fine while detached
warlock soulshards also work
druid feral form combo points also work

Make sure you have them enabled, and also reload
