### ISSUE TITLE
[ISSUE]CursorCooldown Error

### ISSUE THREAD

**Issue by TehGOOSE** [eltreum0/eltruism#165]
**Describe the bug**
Seems to happen when im testing on dummies, and I open with a keybind of Shift+1 get the bug sound and then this error is produced:
17x ...ns/ElvUI_EltreumUI/Modules/Cursor/CursorCooldown.lua:330: attempt to index local 'spellData' (a nil value)
[string "@ElvUI_EltreumUI/Modules/Cursor/CursorCooldown.lua"]:330: in function <...ns/ElvUI_EltreumUI/Modules/Cursor/CursorCooldown.lua:326>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `CastSpellByName'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:1250: in function `?'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5420: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5386>
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5092: in function `ChatEdit_SendText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:3267: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:3261>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `UseAction'
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:342: in function `handler'
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:667: in function <...ddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:649>
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:681: in function <...ddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:674>
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:723: in function <...ddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:707>
[string "=[C]"]: ?
[string "@Blizzard_FrameXML/SecureHandlers.lua"]:266: in function <Blizzard_FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Blizzard_FrameXML/SecureHandlers.lua"]:296: in function <Blizzard_FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals:
self = <table> {
 modules = <table> {
 }
 Spec = 62
 RightChatIsSkinned = true
 name = "ElvUI_ElvUI_EltreumUI"
 defaultModuleState = true
 LeftChatIsSkinned = true
 minimapIsSkinned = true
 ischarpanelHooked = true
 Config = <table> {
 }
 ConfigModeAddedEltruism = true
 baseName = "ElvUI_EltreumUI"
 hooks = <table> {
 }
 Version = "4.1.9"
 InstallerData = <table> {
 }
 CreditsList = <table> {
 }
 enabledState = true
 Name = "|cff7fb2ffE|r|cff8ac2ffl|r|cff95d2fft|r|cffa0e2ffr|r|cffaaf2ffu|r|cffaaf2ffi|r|cffaaf2ffs|r|cffaaf2ffm|r"
 defaultModuleLibraries = <table> {
 }
 orderedModules = <table> {
 }
 moduleName = "ElvUI_EltreumUI"
 ZoneSkinned = true
}
spell = "item:191907"
spellData = nil
(*temporary) = "item:191907"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'spellData' (a nil value)"
E = <table> {
 mylevel = 70
 Bags = <table> {
 }
 privateVars = <table> {
 }
 modules = <table> {
 }
 myspecRole = "DAMAGER"
 PriestColors = <table> {
 }
 db = <table> {
 }
 Layout = <table> {
 }
 Distributor = <table> {
 }
 MountText = <table> {
 }
 INCOMPATIBLE_ADDONS = <table> {
 }
 TimeIndicatorColors = <table> {
 }
 WorldMap = <table> {
 }
 TimeColors = <table> {
 }
 ShortValueDec = "%.0f"
 oUF = <table> {
 }
 Classic = false
 myrole = "DAMAGER"
 UFParent = ElvUFParent {
 }
 wowtoc = 110000
 InfoColor2 = "|cff9b9b9b"
 myname = "Tehgoose"
 ActionBars = <table> {
 }
 screenHeight = 1440
 twoPixelsPlease = false
 ConfigModeLayouts = <table> {
 }
 DataTexts = <table> {
 }
 ClassName = <table> {
 }
 CreatureTypes = <table> {
 }
 Auras = <table> {
 }
 private = <table> {
 }
 ReverseTimer = <table> {
 }
 TagFunctions = <table> {
 }
 myClassID = 8
 UnlocalizedClasses = <table> {
 }
 MinimapSize = 265
 snapBars = <table> {
 }
 hooks = <table> {
 }
 SpecName = <table> {
 }
 GemTypeInfo = <table> {
 }
 StyleFilterDefaults = <table> {
 }
 physicalWidth = 2560
 versionString = "13.71"
 LSM = <table> {
 }
 InfoColor = "|cff1784d1"
 CreatedMovers = <table> {
 }
 myLocalizedFaction = "Horde"
 myrace = "Tauren"
 StaticPopup_DisplayedFrames = <table> {
 }
 VehicleLocks = <table> {
 }
 myLocalizedRace = "Tauren"
 myclass = "MAGE"
 wowdate = "Jul 23 2024"
 PopupDialogs = <table> {
 }
 Chat = <table> {
 }
 myrealm = "Hyjal"
 LayoutMoverPositions = <table> {
 }
 global = <table> {
 }
 orderedModules = <table> {
 }
 Misc = <table> {
 }
 UnitFrames = <table> {
 }
 uiscale = 0.533333
 TBC = false
 AnimElastic = <table> {
 }
 media = <table> {
 }
 data = <table> {
 }
 Options = <table> {
 }
 toc = 110000
 HiddenFrame = Frame {
 }
 Media = <table> {
 }
 name = "ElvUI"
 TimeFormats = <table> {
 }
 ShortPrefixStyles = <table> {
 }
 versionDev = false
 Blizzard = <table> {
 }
 MountDragons = <table> {
 }
 TotemTracker = <table> {
 }
 RegisteredCooldowns = <table> {
 }
 SpecInfoBySpecID = <table> {
 }
 ObjectEventTable = <table> {
 }
 title = "|cff1784d1ElvUI|r"
 EditorMode = <table> {
 }
 MapInfo = <table> {
 }
 frames = <table> {
 }
 physicalHeight = 1440
 NewSignNoWhatsNew = "|TInterface\OptionsFrame\UI-OptionsFrame-NewFeatureIcon:14:14:0:0|t"
 Retail = true
 MountIDs = <table> {
 }
 AnimShake = <table> {
 }
 DisabledMovers = <table> {
 }
 mult = 1
 UserList = <table> {
 }
 PixelMode = true
 serverID = 3661
 PrivateAuras = <table> {
 }
 MediaUpdated = true
 Spacing = 0
 myspecName = "Arcane"
 GetFormattedTextStyles = <table> {
 }
 DEFAULT_FILTER = <table> {
 }
 myspecIcon = 135932
 staggerUpdateRunning = false
 ConfigTooltip = ElvUI_ConfigTooltip {
 }
 SpecInfoBySpecClass = <table> {
 }
 initialized = true
 statusBars = <table> {
 }
 charSettings = <table> {
 }
 myguid = "Player-3661-0949926D"
 loadedtime = 549583.916000
 myspecID = 62
 texts = <table> {
 }
 Border = 1
 EasyMenu = ElvUI_EasyMenu {
 }
 resolution = "2560x1440"
 SpellBookTooltip = ElvUI_SpellBookTooltip {
 }
 baseName = "ElvUI"
 Filters = <table> {
 }
 TagInfo = <table> {
 }
 InverseAnchors = <table> {
 }
 ConfigModeLocalizedStrings = <table> {
 }
 ModuleCopy = <table> {
 }
 callbacks = <t

**Addon Versions (please complete the following information):**
 - ElvUI version: [13.72]
 - Eltruism version: [4.1.9.1]
 - JibberishUI 1.2.6
 - Windtools 3.59-alpha-4
 - Location Plus 2.85 (w/ Edit suggest from github)
 - Ratio minimap Auras 1.15
 -

**Additional context**
Other then throwing an error I dont think it restricts me from doing anything, spells still go off - but I wanted to share anyways. Hope it helps!

Love what you guys do!

**Comment by eltreum0** [comment]
This was fixed in this commit https://github.com/eltreum0/eltruism/commit/54aa782f7a479585a7b53666604829b22329e33e

will be on the next version

**Comment by TehGOOSE** [comment]
Youre amazing! Keep up the good work!
