### ISSUE TITLE
[ISSUE] Cell Gradient Skin missing from pets (on solo most likely group as well)

### ISSUE THREAD

**Issue by AngelosNaoumis** [eltreum0/eltruism#167]
**Describe the bug**
Basically gradient colors are missing from pet frame

**To Reproduce**
1. Enable Cell skin
2. Enable show on solo option
3. Log to a warlock or hunter

**Expected behavior**
Same color of gradient to be applied to player & pet

**Screenshots**
![image](https://github.com/user-attachments/assets/9ec9c4cb-2c6b-494e-a9a2-bd709bd92b2d)

**Addon Versions (please complete the following information):**
 - ElvUI version: 13.73
 - Eltruism version: 4.2.0

**Additional context**

**Comment by eltreum0** [comment]
Do /fstack on the pet and show the tooltip with the names of the frames (with the pet one being the one being moused over)

**Comment by AngelosNaoumis** [comment]
Solo
![image](https://github.com/user-attachments/assets/7b9e63ec-57a5-4c0e-b93d-52afbd30b7d1)
In Party
![image](https://github.com/user-attachments/assets/6664bfb2-7013-45a6-a3cc-acff3b558948)
