### ISSUE TITLE
[ISSUE] Raid Frame Shadows

### ISSUE THREAD

**Issue by Jimmybuckets** [eltreum0/eltruism#169]
**Describe the bug**
The shadows only works for the first group when using "Raid-wide sorting". Shadow works for all groups when you dont have raid wide sorting on.

**To Reproduce**
3. Do '....'

**Expected behavior**

**Screenshots**

**Addon Versions (please complete the following information):**
 - ElvUI version: [e.g. 12.60]
 - Eltruism version: [e.g. 3.9.0]
 - Any other addons used: [e.g. Details, BigWigs, ProjectAzilroka and so on]

**Additional context**

**Comment by eltreum0** [comment]
its not recommended to use raid wide sorting as it can and will cause issues, this is known by elvui too and its not a recommended setting there too
