### ISSUE TITLE
[ISSUE]

### ISSUE THREAD

**Issue by TotalHamman** [eltreum0/eltruism#170]
**Describe the bug**
LUA Error when logging into character in Garrison.

```
Message: ...ce/AddOns/ElvUI_EltreumUI/Modules/Misc/Instances.lua:35: attempt to index field 'instances' (a nil value)
Time: Fri Aug 16 16:02:22 2024
Count: 3
Stack: ...ce/AddOns/ElvUI_EltreumUI/Modules/Misc/Instances.lua:35: attempt to index field 'instances' (a nil value)
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_EltreumUI/Modules/Misc/Instances.lua"]:35: in function <...ce/AddOns/ElvUI_EltreumUI/Modules/Misc/Instances.lua:29>

Locals: 
```

**To Reproduce**
Logout in Garrison and then log back in.

**Expected behavior**
No errors

**Screenshots**
No Screenshot Necessary

**Addon Versions (please complete the following information):**
 - ElvUI version: 13.74
 - Eltruism version: 4.2.1
 - Any other addons used: WindTools 3.64, Shadow and Light 4.81, Nuts & Bolts 1.48

**Additional context**

**Comment by eltreum0** [comment]
Interesting that you got line 35 while i got 38, looking into it

**Comment by eltreum0** [comment]
Ok i seem to have found the issue, when on a garrison now you apparently first zone into Azeroth itself (947) and then the expansion zone such as Draenor (572)
