### ISSUE TITLE
[REQUEST] Disable raid frames in battlegrounds and party frames in arenas

### ISSUE THREAD

**Issue by RealJig** [eltreum0/eltruism#174]
**Is your feature request related to a problem? Please describe.**
I use gladiusEx and battlegroundenemies and I would like to use those addons for my teammates unitframes and not have the ElvUI ones show up

**Describe the solution you'd like**
Automatically disable the raid and party frames when entering an arena/BG

![World Of Warcraft Screenshot 2024 09 05 - 02 15 32 19](https://github.com/user-attachments/assets/18a44f68-1f53-499a-96e4-02b2c1d26a65)

**Comment by eltreum0** [comment]
that option already exists in Eltruism >Misc > Combat > hide raid frames in battlegrounds due to addons like battleground enemies

**Comment by RealJig** [comment]
Oh whoops I didn't see that, perhaps the options should be enabled when applying the gladiusex and battlegroundenemies profiles.

**Comment by eltreum0** [comment]
not likely because people usually enable those addons when they are going into pvp and have them disabled in raids/dungeons, if enabled then raids would disappear and they would complain
