### ISSUE TITLE
[ISSUE]Eltruism simply refuses to change my health bar to a green color as set when in good health, and as my health goes down the green bar should continually get shorter with a black background. I have tried and tried and wasted many hours to get this fixed. I simply want my health bar to work EXACTLY how Blizzard have set it up.

### ISSUE THREAD

**Issue by Tronutopia** [eltreum0/eltruism#176]
**Describe the bug**

**To Reproduce**
3. Do '....'

**Expected behavior**

**Screenshots**

**Addon Versions (please complete the following information):**
 - ElvUI version: [e.g. 12.60]
 - Eltruism version: [e.g. 3.9.0]
 - Any other addons used: [e.g. Details, BigWigs, ProjectAzilroka and so on]

**Additional context**

**Comment by eltreum0** [comment]
This is a setting in elvui, the way my profile works by default is class colored backgrounds with black health (so called dark mode), the mode you want is the reverse: class colored health with black background (so called light mode)

A quick swap between them is /eltruism color
