### ISSUE TITLE
[ISSUE] Addon bugs me about game version every time I zone, even though there isn't an update

### ISSUE THREAD

**Issue by thunderchylde** [eltreum0/eltruism#177]
**Describe the bug**
The addon has a pop up every. time. I. zone. about game version. It's ridiculous that it isn't at least only per session, and especially not configurable, ESPECIALLY when there isn't an update that will remove it.

**To Reproduce**
1. Have the current version of the addon with the current version of WoW Classic SoD

**Expected behavior**
I expect to not be hassled every time I go through a loading screen.

**Screenshots**

**Addon Versions (please complete the following information):**
 - ElvUI version: 13.81
 - Eltruism version: 4.2.5
 - Any other addons used: a bunch that are irrelevant to the issue at hand

**Additional context**

**Comment by eltreum0** [comment]
this is fixed in dev, its due to the .toc on release having the old version

There will be an update later today that fixes this

**Comment by eltreum0** [comment]
fixed in 4.2.6
