### ISSUE TITLE
Profession skin 

### ISSUE THREAD

**Issue by Namzra** [eltreum0/eltruism#76]
Issue where item description is not shown when profession skin is activated
![image](https://user-images.githubusercontent.com/18156888/198370499-d77765ba-3d3d-435f-82b1-d8215b30f0dc.png)
![image](https://user-images.githubusercontent.com/18156888/198370573-4f0f67a1-fdb2-4971-9579-ef3ce1c44c0a.png)

With profession skin desactivated :
![image](https://user-images.githubusercontent.com/18156888/198370715-5aa2c6ce-2090-4c30-814e-396db8b51cff.png)
![image](https://user-images.githubusercontent.com/18156888/198370750-7e7acc6f-063b-479d-a26f-aab8777393f7.png)

![image](https://user-images.githubusercontent.com/18156888/198370817-78fce207-f988-435e-8f51-a4cc7b9d0095.png)

**Comment by eltreum0** [comment]
Do you have any other profession addon? Because the text is still showing for me
![image](https://user-images.githubusercontent.com/30246110/198499346-967bc6d7-8dfc-496d-b467-eb8aa56e7495.png)

**Comment by eltreum0** [comment]
Fixed with the commit
