### ISSUE TITLE
[ISSUE]

### ISSUE THREAD

**Issue by spagno** [eltreum0/eltruism#79]
**Describe the bug**

if you use gladiusex with eltruism, the right and left click on the enemy arena frame doesn't work
it seems not to be a problem with gladiusex because with elvui or without any other addons it works correctly

also the eltruism arenaframe are still enabled and this cause to have 2 different frames

**To Reproduce**
1. install elvui dev
2. install gladiusex
3. install eltruism
4. setup eltriusm and import gladiusex profile

**Expected behavior**
arena frames managed completey by gladiusex.  if you click with the right button it targets, with the left button it focuses

**Addon Versions (please complete the following information):**
 - ElvUI version: latest development
 - AddonSkins version: 4.60
 - Any other addons used: Details, DBM, ProjectAzilroka, Clique, ArkInventory, Capping, DynamicCam, WindTools, Nameplate SCT, ElvUI FCT, gladiusex, MRT, Shadow&Light

**Comment by eltreum0** [comment]
Should be fixed now

**Comment by eltreum0** [comment]
There seems to be an issue with gladiusEX to make the clicking work, not sure why it doesnt work with elvui

**Comment by spagno** [comment]
the current elvui has a problem with the arena frame: the elvui dev fixes it and gladiusEX works correctly

**Comment by spagno** [comment]
I'm using elvui dev because it fixes an arena frame problem. If you try elvui dev and gladiusEX with the default profile it should work. with the eltruism profile it doesn't. In eltruism it doesn't work at all, also with the default profile

**Comment by eltreum0** [comment]
there seems to be an unknown issue with elvui causing it, will have to wait for that
