### ISSUE TITLE
Unit Frames - Backdrops - Backdrop Alpha Defaults to .7 after reloads or relogs [ISSUE]

### ISSUE THREAD

**Issue by rjshelton** [eltreum0/eltruism#80]
**Describe the bug**

Unitframe backdrop alpha always gets set to 0.7 after reloads or relogs.

**To Reproduce**
1. Go to Eltruism
2. Click on Unitframes
3. Scroll to Backdrops
4. Set Alpha to 1
5. Relog or Reload

**Expected behavior**
Alpha should stay 1, not default back to 0.7.  I check the settings in the text file in the addons and it looks like it's set to 1, but in game it's 0.7 again.

**Screenshots**

**Addon Versions (please complete the following information):**
 - ElvUI version: 12.00
 - AddonSkins version:  Eltruism 3.5.5.1
 - Any other addons used: Details, Weak auras, Gladdy, Pally Power, Plater.

**Additional context**

**Comment by rjshelton** [comment]
![Screenshot 2022-11-04 161332](https://user-images.githubusercontent.com/26284076/200087825-8062ea87-a2e2-4a02-a072-5a73798c1ffe.png)

This is the setting in question.

**Comment by eltreum0** [comment]
It's not a bug, you have auto adjust borders enabled which sets the backdrop to 0.7 on reload
