### ISSUE TITLE
Incompability between WindTools World Map Scaling and Eltruism

### ISSUE THREAD

**Issue by dralsoM** [eltreum0/eltruism#88]
The World Map Scaling option of WindTools, is unchecked by Eltruism on every /reloadui.

![WoWScrnShot_122522_173447](https://user-images.githubusercontent.com/25705098/209475756-bae99cd9-208c-40b9-bb08-4f31bcb0e285.jpg)
![WoWScrnShot_122522_173748](https://user-images.githubusercontent.com/25705098/209475762-91f21fe6-bfec-4d05-9331-2a1da0aa974b.jpg)

- ElvUI version: 13.15
 - WindTools version: 3.16
 - Eltruism version: 3.6.8

**Comment by eltreum0** [comment]
it is unsigned because eltruism also has a map scale in eltruism > Quests > Quest Detail Scale, in order to not have both trying to assign a value and causing issues one is disabled

it's set in quests because in retail the world map is not a separate frame and is attached to the quests

**Comment by dralsoM** [comment]
but I totally disabled this tab so there is no conflict whatsoever

**Comment by dralsoM** [comment]
And if I only want to use the scaling option of Eltruism (because I can't use the one of WindTools) but the objective tracker of WindTools, I can't. It is possible to enable the scaling option without the objective tracker skin please ? It will solve everything.

**Comment by eltreum0** [comment]
added the option the recent commit
