### ISSUE TITLE
Constantly Action bar is locked

### ISSUE THREAD

**Issue by reyard** [eltreum0/eltruism#92]
_**Describe the bug**_
**When I play with my mage and do a teleport or portal spell, some ability buttons are locked and cannot be pressed on the keyboard, they can only be clicked, I need to use the /reload command to fix it.**

_*To Reproduce**_
**1. Use teleport to stormwind
2. Use Portal to Valdrakken
3. Try all action bar buttons
4. Use a Dragon mount and try use his skills**

_**Expected behavior**_
It should'nt be locked

_**Screenshots**_

_**Addon Versions (please complete the following information):**_
 - ElvUI version: **13.23**
 - AddonSkins version: **4.62**
 - Eltruism version: **3.7.1**

_**Additional context**_
**1x [ADDON_ACTION_FORBIDDEN] El addon 'ElvUI_EltreumUI' you tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `UseAction'
[string "@FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@FrameXML/ActionButton.lua"]:89: in function `TryUseActionButton'
[string "@FrameXML/ActionButton.lua"]:124: in function `ActionButtonDown'
[string "ACTIONBUTTON9"]:2: in function <[string "ACTIONBUTTON9"]:1>**

**Comment by eltreum0** [comment]
Read more about taints here https://wowpedia.fandom.com/wiki/Secure_Execution_and_Tainting

Its not caused by Eltruism but any other addon you have, you can use the command

/eltruismdebug on

To test with only eltruism, you can also try installing this https://www.curseforge.com/wow/addons/notaint2 to help prevent taints
